version: "3"
services:
  web:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/data/
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=rasp-bundle.com
      - NGINX_PORT=80
    networks: 
      - webnet
    command: [nginx-debug, '-g', 'daemon off;']

networks: 
    webnet: